export const LOADING_INITIAL_IMAGES = {
  REQUEST: "LOADING_INITIAL_IMAGES_REQUEST",
  LOADING: "LOADING_INITIAL_IMAGES_LOADING",
  SUCCESS: "LOADING_INITIAL_IMAGES_SUCCESS",
  ERROR: "LOADING_INITIAL_IMAGES_ERROR",
};
