const products = [
  {
    id: 1,
    name: "Bluetooth Speaker",
    image: "../images/bluetooth_speaker.jpg",
    description: "Bluetooth speakers with high quality audio",
    brand: "boAt",
    category: "Electronics",
    price: 1200,
    rating: 4.5,
    CountInStock: 2,
  },
  {
    id: 2,
    name: "Gopro Camera",
    image: "../images/gopro_camera.jpg",
    description: "camera with high quality video and audio",
    brand: "GoPro",
    category: "Electronics",
    price: 2000,
    rating: 3.5,
    CountInStock: 10,
  },
  {
    id: 3,
    name: "Joystick",
    image: "../images/joystick.jpg",
    description: "jyostick for play station",
    brand: "micrpsoft",
    category: "Electronics",
    price: 10000,
    rating: 4.5,
    CountInStock: 5,
  },
  {
    id: 4,
    name: "Mouse",
    image: "../images/mouse.jpg",
    description: "logitech wireless  mouse for Desktops and Laptops",
    brand: "logitech",
    category: "Electronics",
    price: 1500,
    rating: 4.5,
    CountInStock: 5,
  },
  {
    id: 5,
    name: "External Hard Disk",
    image: "../images/External_Hard_Disk.jpg",
    description: "External Hard Disk for Desktops and Laptops",
    brand: "kingstone",
    category: "Electronics",
    price: 8000,
    rating: 4.5,
    CountInStock: 6,
  },
  {
    id: 6,
    name: "Smart Watch",
    image: "../images/smart_watch.jpg",
    description: "smartwatch for health and fitness",
    brand: "noise",
    category: "Electronics",
    price: 1200,
    rating: 4.5,
    CountInStock: 0,
  },
];

export default products;
